
project_structure:
    build: build
    contracts: contracts
    interfaces: interfaces
    reports: reports
    scripts: scripts
    tests: tests

dotenv: .env

networks:
    default: development

    development:
        gas_limit: max
        gas_buffer: 1
        gas_price: 0
        max_fee: null
        priority_fee: null
        reverting_tx_gas_limit: max
        default_contract_owner: true
        cmd_settings:
          unlock:
            - 0x6B175474E89094C44Da98b954EedeAC495271d0F

    live:
        gas_limit: auto
        gas_buffer: 1.1
        gas_price: auto
        max_fee: null
        priority_fee: null
        reverting_tx_gas_limit: false
        default_contract_owner: false

compiler:
  evm_version: null
  solc:
    version: null
    optimizer:
      enabled: true
      runs: 1500
    remappings: 
      - "@OpenZeppelin=OpenZeppelin/openzeppelin-contracts@4.9.3"
      - "@uniswap/v3-core=Uniswap/v3-core@6562c52e8f75f0c10f9deaf44861847585fc8129"
      - "@uniswap/v3-periphery=Uniswap/v3-periphery@b325bb0905d922ae61fcc7df85ee802e8df5e96c"
  vyper:
    version: null

console:
  show_colors: true
  color_style: monokai
  auto_suggest: true
  completions: true
  editing_mode: emacs

reports:
  exclude_paths: null
  exclude_contracts: null
  only_include_project: true

hypothesis:
  deadline: null
  max_examples: 50
  report_multiple_bugs: False
  stateful_step_count: 10
  phases:
    explicit: true
    reuse: true
    generate: true
    target: true
    shrink: true

autofetch_sources: false
dependencies:
 - OpenZeppelin/openzeppelin-contracts@4.9.3
 - Uniswap/v3-core@6562c52e8f75f0c10f9deaf44861847585fc8129
 - Uniswap/v3-periphery@b325bb0905d922ae61fcc7df85ee802e8df5e96c
dev_deployment_artifacts: falsebro

